version: '3.7'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
      - '/app/.next'
    ports:
      - '3000:3000'
    environment:
        NODE_ENV: development
    depends_on:
      - backend
    links:
      - backend


  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    environment:
        NODE_ENV: development
        MYSQL_HOST: db
        MYSQL_ROOT_PASSWORD: yazi123456
        MYSQL_DATABASE: covid_tn
        MYSQL_USER: covid
        MYSQL_PASSWORD: covid
    depends_on:
      - db


  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: yazi123456
      MYSQL_DATABASE: covid_tn
      MYSQL_USER: covid
      MYSQL_PASSWORD: covid

  phpmyadmin:
    container_name: phpmyadmin
    image:  phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    links:
      - db


volumes:
  db_data: {}

networks:
  default:
    external:
      name: covid_globalnet